#!/bin/bash
if [ $# -lt 1 -o $# -gt 3 ]
then
  echo "Error in $0 - Invalid Usage"
  echo "Syntax: $0 application_name <github_username>"
  exit
fi

mkdir $1
mkdir $1/js
mkdir $1/web
mkdir $1/web/public
mkdir $1/web/public/images
mkdir $1/web/public/javascripts
mkdir $1/web/public/stylesheets
echo "<html><head></head><body><p>I am in web/public, where are you?</p><p>Remove me</p></body></html>" > $1/web/public/index.html
echo "system.use(\"com.joyent.Sammy\");\nGET(/\/*/, function()  { return \"Hello World\"; });" > $1/js/bootstrap.js

cd $1
git init
git add .
git commit -a -m "Adding the initial directory structure."
if [ $# -ge 2 ]
then
  git remote add origin git@github.com:$2/$1.git
  git push origin master
fi

git remote add smart git@git.smart.joyent.com:$1.smart.joyent.com.git
git push smart master
